### ISSUE TITLE
Support dependency repository use scheme acr://

### ISSUE THREAD

**Issue by liuyangc3** [AliyunContainerService/helm-acr#10]
for example
```
# Chart.yaml
dependencies:
- name: mychart
  version: "1.2.3"
  repository: "acr://example.com/charts"
```
